### ISSUE TITLE
Clicking outside the clouds (the ones that point to repos) should make them go back to their original position

### ISSUE THREAD

**Issue by ceiroa** [SalesforceFoundation/salesforcefoundation.github.io#1]

**Comment by dextermilo** [comment]
Can you describe why this is a bug?

**Comment by ceiroa** [comment]
It's not a bug. I labeled it as enhancement. I can give it a different label if you prefer. :-)

**Comment by dextermilo** [comment]
I may have clicked on it too fast, sorry :)

**Comment by ceiroa** [comment]
No need for it with the new design.
